/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List artists
         * @description Get a list of all artists with pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit number of artists returned */
                    limit?: number;
                    /** @description Offset for pagination */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Artist"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create artist
         * @description Create a new artist
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Artist to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.ArtistDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Artist"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete artist
         * @description Delete an artist by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Artist ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update artist
         * @description Update an artist by ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Artist ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Artist fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.ArtistDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Artist"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List authors
         * @description Get a list of all authors with pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit number of authors returned */
                    limit?: number;
                    /** @description Offset for pagination */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create author
         * @description Create a new author
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Author to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.AuthorDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/authors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete author
         * @description Delete an author by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update author
         * @description Update an author by ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Updated author data */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.AuthorDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books
         * @description Get a list of all books with pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit number of books returned */
                    limit?: number;
                    /** @description Offset for pagination */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Book"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create book
         * @description Create a new book
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Book to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.BookDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Book"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete book
         * @description Delete a book by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update book
         * @description Update a book by ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Book fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.BookDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Book"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List covers
         * @description Get a list of all covers with pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit number of covers returned */
                    limit?: number;
                    /** @description Offset for pagination */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Cover"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create cover
         * @description Create a new cover
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Cover to create */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.CoverDTO"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Cover"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/covers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete cover
         * @description Delete a cover by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cover ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update cover
         * @description Update a cover by ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cover ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Cover fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes_admin.CoverDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Cover"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login user and return JWT token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_server_routes.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_server_routes.LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout user and clear JWT token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List authors
         * @description List all authors
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_server_types.ListAuthorResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * Create author
         * @description Create a new author
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Author object */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get author
         * @description Get author by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Author ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books
         * @description List all books
         */
        get: {
            parameters: {
                query?: {
                    /** @description Limit */
                    limit?: number;
                    /** @description Offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_server_types.ListBookResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get book
         * @description Get book by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Book"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "go-playground_internal_database_models.Artist": {
            Covers?: components["schemas"]["go-playground_internal_database_models.Cover"][];
            CreatedAt?: string;
            DeletedAt?: components["schemas"]["gorm.DeletedAt"];
            ID?: number;
            UpdatedAt?: string;
            first_name: string;
            last_name: string;
        };
        "go-playground_internal_database_models.Author": {
            Books?: components["schemas"]["go-playground_internal_database_models.Book"][];
            CreatedAt?: string;
            DeletedAt?: components["schemas"]["gorm.DeletedAt"];
            ID?: number;
            UpdatedAt?: string;
            first_name: string;
            last_name: string;
        };
        "go-playground_internal_database_models.Book": {
            Cover?: components["schemas"]["go-playground_internal_database_models.Cover"];
            CreatedAt?: string;
            DeletedAt?: components["schemas"]["gorm.DeletedAt"];
            ID?: number;
            UpdatedAt?: string;
            author?: components["schemas"]["go-playground_internal_database_models.Author"];
            author_id?: number;
            description: string;
            digital_only: boolean;
            genres?: components["schemas"]["go-playground_internal_database_models.Genre"][];
            isbn: string;
            pages: number;
            price: number;
            published_date: string;
            title: string;
        };
        "go-playground_internal_database_models.Cover": {
            Artists?: components["schemas"]["go-playground_internal_database_models.Artist"][];
            CreatedAt?: string;
            DeletedAt?: components["schemas"]["gorm.DeletedAt"];
            ID?: number;
            UpdatedAt?: string;
            book_id: number;
            design_ideas: components["schemas"]["sql.NullString"];
            image_url?: components["schemas"]["sql.NullString"];
        };
        "go-playground_internal_database_models.Genre": {
            CreatedAt?: string;
            DeletedAt?: components["schemas"]["gorm.DeletedAt"];
            ID?: number;
            UpdatedAt?: string;
            books?: components["schemas"]["go-playground_internal_database_models.Book"][];
            name: string;
        };
        "go-playground_internal_server_types.ListAuthorResponse": {
            first_name?: string;
            id?: number;
            last_name?: string;
        };
        "go-playground_internal_server_types.ListBookResponse": {
            Author?: components["schemas"]["go-playground_internal_server_types.ListAuthorResponse"];
            Cover?: components["schemas"]["go-playground_internal_server_types.ListCoverResponse"];
            description?: string;
            digital_only?: boolean;
            genres?: string[];
            id?: number;
            isbn?: string;
            pages?: number;
            price?: number;
            published_date?: string;
            title?: string;
        };
        "go-playground_internal_server_types.ListCoverResponse": {
            id?: number;
            image_url?: string;
        };
        "gorm.DeletedAt": {
            Time?: string;
            /** @description Valid is true if Time is not NULL */
            Valid?: boolean;
        };
        "internal_server_routes.LoginRequest": {
            password: string;
            username: string;
        };
        "internal_server_routes.LoginResponse": {
            authToken: string;
        };
        "internal_server_routes_admin.ArtistDTO": {
            first_name?: string;
            /** @description Added ID field for validation purposes */
            id?: number;
            last_name?: string;
        };
        "internal_server_routes_admin.AuthorDTO": {
            first_name?: string;
            /** @description Added ID field for validation purposes */
            id?: number;
            last_name?: string;
        };
        "internal_server_routes_admin.BookDTO": {
            author_id?: number;
            description?: string;
            digital_only?: boolean;
            /** @description Added ID field for validation purposes */
            id?: number;
            isbn?: string;
            pages?: number;
            price?: number;
            published_date?: string;
            title?: string;
        };
        "internal_server_routes_admin.CoverDTO": {
            artist_ids?: number[];
            book_id?: number;
            design_ideas?: string;
            /** @description Added ID field for validation purposes */
            id?: number;
            image_url?: string;
        };
        "sql.NullString": {
            String?: string;
            /** @description Valid is true if String is not NULL */
            Valid?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
