/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List authors
         * @description List all authors
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * Create author
         * @description Create a new author
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Author object */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["go-playground_internal_database_models.Author"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "go-playground_internal_database_models.Author": {
            books?: components["schemas"]["go-playground_internal_database_models.Book"][];
            createdAt?: string;
            deletedAt?: components["schemas"]["gorm.DeletedAt"];
            firstname: string;
            id?: number;
            lastname: string;
            updatedAt?: string;
        };
        "go-playground_internal_database_models.Book": {
            authorID?: number;
            createdAt?: string;
            deletedAt?: components["schemas"]["gorm.DeletedAt"];
            id?: number;
            published_date: string;
            title: string;
            updatedAt?: string;
        };
        "gorm.DeletedAt": {
            time?: string;
            /** @description Valid is true if Time is not NULL */
            valid?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
